### ISSUE TITLE
Travis CI intergation

### ISSUE THREAD

**Issue by Ullaakut** [Ullaakut/AdventureBot#4]
## Purpose
Having automated deployment of our Docker image on the Docker Hub integrated into a build and testing pipeline will make sure that all pushed code is functional and immediately profitable to the users.

It will also allow us to automatically see the testing status of Pull Requests through Github like such

![screen shot 2017-01-31 at 13 18 22](https://cloud.githubusercontent.com/assets/6976628/22464561/c637f408-e7b7-11e6-8d85-486428df3fb0.png)

## Instructions
1. Add a `.travis.yml` file at the root of the repository
2. Log into [Travis](https://travis-ci.org/) using your GitHub account
3. Grant Travis access to AdventureBot
4. If the issue https://github.com/Ullaakut/AdventureBot/issues/2 has been done, make sure there is a build job and a test job that fails if the API tests are unsuccessful

## How to test it
* Create a pull request
* You should see the travis checks running
* On https://travis-ci.org/Ullaakut/AdventureBot/builds you should see the job running
* Ask me to setup my Docker Hub credentials on Travis in order to be able to deploy our Docker Image
* At the end it should look like this : 

![screen shot 2017-01-31 at 13 21 45](https://cloud.githubusercontent.com/assets/6976628/22464650/3d02e26e-e7b8-11e6-95a8-f2e9701c6932.png)

## Examples
All of the work of this integration is to setup the `.travis.yml` file correctly.

Here is an example : 

```
language: generic
sudo: required
dist: trusty

before_install:
- echo "Testing Docker Hub credentials"
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- echo "Docker Hub credentials are working"
- sudo apt-get update -qq
- sudo apt-get install -y whatever-we-need

matrix:
  include:
    - os: linux
      env: TEST_TYPE='BUILD' WORKDIR='deployment'
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: TEST_TYPE='TEST' WORKDIR='test'
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test

script:
- cd ${WORKDIR}
- ./a_build_script.sh
- if [[ "$TEST_TYPE" == "BUILD" ]]; then docker build -t AdventureBot . && docker run AdventureBot; else ./a_test_script.sh ; fi

after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub" && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker tag AdventureBot $DOCKER_REPO:latest && docker tag AdventureBot $DOCKER_REPO:$TRAVIS_TAG && docker push $DOCKER_REPO; fi
```
